export const RECEIVED_USER = 'RECEIVED_USER'

export const RECEIVED_DOCUMENTS = 'RECEIVED_DOCUMENTS'
export const RECEIVED_DOCUMENT = 'RECEIVED_DOCUMENT'

export const RECEIVED_MODELS = 'RECEIVED_MODELS'
export const RECEIVED_MODEL = 'RECEIVED_MODEL'

export const RECEIVED_ACTIVITIES = 'RECEIVED_ACTIVITIES'
export const RECEIVED_ACTIVITY = 'RECEIVED_ACTIVITY'
